FROM node:latest

WORKDIR /container-node

RUN git clone https://github.com/EduardoAAzevedo/ServGuard.git

WORKDIR /container-node/ServGuard

RUN npm install

EXPOSE 8080

CMD ["sh", "-c", "git pull && npm start"]