FROM node:latest

WORKDIR /container-node

RUN git clone https://github.com/ServGuard-org/ServGuard-WebSite.git

WORKDIR /container-node/ServGuard-WebSite

RUN npm install

EXPOSE 8080

CMD ["sh", "-c", "git pull && npm start"]